### ISSUE TITLE
Potential bug: Changing cdil, csw, etc. values yields identical outputs for Calc2Node function

### ISSUE THREAD

**Issue by praftery** [marcelschweiker/comf#3]
First off, thank you for creating this convenient R package and sharing it with the community - I appreciate it.

I may have uncovered a bug. It appears that changing any of the non environmental/personal inputs has **no** effect on the outputs. For example, changing cdil from 100 to 200 gives the exact same output vector:

```
calc2Node(35,35, 0.5,clo=0.6,met=1.13, rh=50, cdil=200) == calc2Node(35,35, 0.5,clo=0.6,met=1.13, rh=50, cdil=100)
       
et  set tsens disc   pd   ps  pts pmvg pmvstar
[1,] TRUE TRUE  TRUE TRUE TRUE TRUE TRUE TRUE    TRUE
```

One additional minor point is that the createCond() function generates a conditions where cdil = 100, however most of the rest of the code base uses cdil =120. For example, the default value for cdil in calc2Node() is 120.

**Comment by marcelschweiker** [comment]
Thanks for spotting this. You are right - that is an error in the calc2Node function. Whatever your input to cdil (and also csw and cstr) will be overwritten by the first lines of that function. I will adjust this asap for the next update.
Meanwhile, a workaround is to acquire the code of this function (simply type "calc2Node" within R), rename it, delete lines 5-7 and use the revised version.

**Comment by marcelschweiker** [comment]
I just made the required changes here: R/fct2Node.r

**Comment by praftery** [comment]
Thanks for the fast response!

**Comment by marcelschweiker** [comment]
Hi there, took some while... Just letting you know that the version 0.1.10 is on CRAN now, which fixed this issue.
