### ISSUE TITLE
The input should be the relative air speed and not the measured one

### ISSUE THREAD

**Issue by FedericoTartarini** [marcelschweiker/comf#54]
@marcelschweiker in both the ISO7730 and AHSRAE55 the input to the PMV is the relative air speed and not the measured one, so we should update the documentation [here](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcPMVPPD.R#L7). 

The same is true for clothing since the input should be the dynamic clothing.
IN pythermalcomfort I am adding this note to the documentation
```
Note: The activity as well as the air speed modify the insulation characteristics
        of the clothing and the adjacent air layer. Consequently, the ISO 7730 states that
        the clothing insulation shall be corrected [2]_. The ASHRAE 55 Standard corrects
        for the effect of the body movement for met equal or higher than 1.2 met using
        the equation clo = Icl × (0.6 + 0.4/met) The dynamic clothing insulation, clo,
        can be calculated using the function
        :py:meth:`pythermalcomfort.utilities.clo_dynamic`.
```

**Comment by marcelschweiker** [comment]
completely agree. Adding this important note was on my list for a long time, but it always flipped through before previous commits to CRAN.

**Comment by marcelschweiker** [comment]
Added notes for relative air velocity and dynamic clothing to documentation of PMVPPD function.
